// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBaudRate() {
  return window['go']['main']['App']['GetBaudRate']();
}

export function GetLowerPort() {
  return window['go']['main']['App']['GetLowerPort']();
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function GetUpperPort() {
  return window['go']['main']['App']['GetUpperPort']();
}

export function ListSerialPorts() {
  return window['go']['main']['App']['ListSerialPorts']();
}

export function LoadSession(arg1) {
  return window['go']['main']['App']['LoadSession'](arg1);
}

export function SaveSession(arg1) {
  return window['go']['main']['App']['SaveSession'](arg1);
}

export function StartCompare() {
  return window['go']['main']['App']['StartCompare']();
}

export function StartRecord(arg1, arg2) {
  return window['go']['main']['App']['StartRecord'](arg1, arg2);
}

export function StartSimulate() {
  return window['go']['main']['App']['StartSimulate']();
}

export function Stop() {
  return window['go']['main']['App']['Stop']();
}
