// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Clear() {
  return window['go']['main']['App']['Clear']();
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function Init() {
  return window['go']['main']['App']['Init']();
}

export function RefreshPorts() {
  return window['go']['main']['App']['RefreshPorts']();
}

export function SelectLowerPort(arg1) {
  return window['go']['main']['App']['SelectLowerPort'](arg1);
}

export function StartCompare() {
  return window['go']['main']['App']['StartCompare']();
}

export function StartRecord() {
  return window['go']['main']['App']['StartRecord']();
}

export function Stop() {
  return window['go']['main']['App']['Stop']();
}
