// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetRecords() {
  return window['go']['main']['App']['GetRecords']();
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function ListSerialPorts() {
  return window['go']['main']['App']['ListSerialPorts']();
}

export function LoadSession(arg1) {
  return window['go']['main']['App']['LoadSession'](arg1);
}

export function SaveSession(arg1) {
  return window['go']['main']['App']['SaveSession'](arg1);
}

export function StartCompare() {
  return window['go']['main']['App']['StartCompare']();
}

export function StartRecording(arg1, arg2) {
  return window['go']['main']['App']['StartRecording'](arg1, arg2);
}

export function StopCompare() {
  return window['go']['main']['App']['StopCompare']();
}

export function StopRecording() {
  return window['go']['main']['App']['StopRecording']();
}
