// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectDevice(arg1:string,arg2:number):Promise<void>;

export function GetBaudRate():Promise<number>;

export function GetRecords():Promise<Array<Record<string, any>>>;

export function GetStats():Promise<number>;

export function ListSerialPorts():Promise<Array<string>>;

export function LoadSession(arg1:string):Promise<void>;

export function SaveSession(arg1:string):Promise<void>;

export function StartCompare():Promise<string>;

export function StartRecord(arg1:string):Promise<string>;

export function StartTest():Promise<string>;

export function Stop():Promise<void>;
