// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';

export function Clear():Promise<api.State>;

export function GetState():Promise<api.State>;

export function Init():Promise<api.State>;

export function RefreshPorts():Promise<api.State>;

export function StartCompare():Promise<api.State>;

export function StartRecord():Promise<api.State>;

export function Stop():Promise<api.State>;
