// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBaudRate():Promise<number>;

export function GetLowerPort():Promise<string>;

export function GetStats():Promise<Record<string, number>>;

export function GetUpperPort():Promise<string>;

export function InitPorts():Promise<Record<string, string>>;

export function ListSerialPorts():Promise<Array<string>>;

export function LoadSession(arg1:string):Promise<number>;

export function SaveSession(arg1:string):Promise<void>;

export function StartCompare():Promise<void>;

export function StartRecord(arg1:string,arg2:number):Promise<void>;

export function StartSimulate():Promise<void>;

export function Stop():Promise<void>;
